### ISSUE TITLE
links to special files (e.g. /dev/disk/by-id) don't get scrubbed

### ISSUE THREAD

**Issue by n1trux** [chaos/scrub#19] opened 2019-08-13 07:57 UTC
Using scrub 2.5.2 in Fedora 29.

When issuing `scrub -p random /dev/disk/by-id/usb-ATA_…`, I get `scrub: warning: /dev/disk/by-id/usb-ATA_… is zero length`.

It's a symlink to a special file, in this case `/dev/sdg`. Why doesn't scrub scrub it? Normal symlinks to regular files or folders work.

**Comment by pete4abw** [comment] 2019-08-22 13:42
The way the test for disk device is written:

> /* Scrub a special file corresponding to a disk.
>  */
> static void
> scrub_disk(char *path, const struct opt_struct *opt)
> {
>     filetype_t ftype = filetype(path);
>     off_t devsize = opt->devsize;
> 
>     assert(ftype == FILE_BLOCK || ftype == FILE_CHAR);

If the file is not a block or char device the program will fail at this point. A link is not such a device. This type of logic makes sense for many reasons, most specifically, a misdirected link to a disk you don't want to scrub.

**Comment by garlick** [comment] 2019-08-22 14:04
This seems like a reasonable use case, and at minimum the error message is wrong/misleading. 
 Maybe the default behavior should be to not follow symlinks, unless a `--follow-symlinks` argument is provided?  E.g.
```
# scrub -p random /dev/disk/by-id/usb-ATA
scrub: skipping symlink /dev/disk/by-id/usb-ATA, consider --follow-symlinks
# scrub -p random --follow-symlinks /dev/disk/by-id/usb-ATA
...
```

**Comment by pete4abw** [comment] 2019-08-22 14:23
While I agree the handling of this case is not consistent, we are talking about entire disks, not a file. I vote for a better, clearer, error message: "Error: Cannot scrub disks via symlinks" to prevent a potentially nasty accident.

if (ftype == FILE_LINK)
 fprintf(stderr,  %s "Error.....");
then you can have the assert

**Comment by garlick** [comment] 2019-08-22 14:32
So never allow a symlink to be followed to a special file?

If you're dealing with a disk array or something and the data you have to work with is a list of  udev aliases (e.g. uuids or whatever), it would be annoying to have to _manually_ follow those links when they're in a secure directory and generally trusted.  In fact the disk id's may be the more reliable way of selecting the right target to scrub, since sometimes the special file names may be dependent on device probing order.

My vote would be to provide some sort of "I know what I'm doing" option to allow the links to be followed.

**Comment by sergio-correia** [comment] 2021-01-26 16:22
Just hit this one as well. 

After some digging, this turns out to be a regression, given scrub 2.2 -- which I had around in some _old_ RHEL version -- worked with symlinks to block devices and this is the commit the introduced the change, as per git bisect: https://github.com/chaos/scrub/commit/01915c442288b4b274261fa07e42e116fb9d6b60

**Comment by sergio-correia** [comment] 2021-01-27 13:01
I posted #20 to address this issue, although from the discussion between @pete4abw and @garlick, perhaps it would be not desirable to restore this behavior. In any case, hopefully the discussion can be restarted and path forward can be agreed.

**Comment by garlick** [comment] 2021-01-27 16:24
Thanks @sergio-correia.  Your change seems reasonable for now.  I haven't had a chance to pay attention here in a while, and I see @pete4abw posted a simple PR in 2019(!) that should be merged.  So if it's OK I'll merge that one first then ask you to rebase on current master, and then yours can go in.

At some point before the next tag, I really really need to get CI going on this project and improve its test capability.  I can't say when that will be but hopefully months not years :-)

**Closed** 2021-01-27 16:55 UTC
